name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: wallckr

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: wallckr
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: wallckr
        shell: bash
        run: |
          west twister -T app -v --inline-logs --integration

      - name: Twister Tests
        working-directory: example-application
        shell: bash
        run: |
          west twister -T tests -v --inline-logs --integration