name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Install simavr
        run: sudo apt-get install -y simavr

      - name: Build firmware
        run: pio run

      - name: Run tests on the native platform
        run: pio test --without-uploading

      - name: Run static code analysis
        run: pio check --skip-packages
